### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by zjhxmjl** [Rongronggg9/kjzhanFakeUA#1]
Hi,美女，有如何使用的FAQ吗？谢谢

**Comment by Rongronggg9** [comment]
在 [Greasy Fork](https://greasyfork.org/zh-CN/scripts/30689) 上安装。
你需要有一个脚本管理器，[这里](https://greasyfork.org/zh-CN/help/installing-user-scripts) 提供了各个浏览器适用的脚本管理器的列表，一旦安装了脚本管理器，你就可以直接安装用户脚本。

**Comment by zjhxmjl** [comment]
> 在 [Greasy Fork](https://greasyfork.org/zh-CN/scripts/30689) 上安装。
> 你需要有一个脚本管理器，[这里](https://greasyfork.org/zh-CN/help/installing-user-scripts) 提供了各个浏览器适用的脚本管理器的列表，一旦安装了脚本管理器，你就可以直接安装用户脚本。

thx,期待新作品！
