### ISSUE TITLE
您好，课件站油猴脚本无法启动，有待更新

### ISSUE THREAD

**Issue by lyjhyjyes** [Rongronggg9/kjzhanFakeUA#2]
http://www.kjzhan.com/meishu/5x/145528.html
可能被屏蔽了吧，可惜了一个好网站

**Comment by Rongronggg9** [comment]
经过验证，本脚本按预期工作，大部分资源都可以正常下载。
在您提供的链接里，本脚本依然按照预期工作，只是该站站长对部分资源采用了微信公众号+百度网盘的分享方式，资源并不在该站服务器上，巧妇难为无米之炊，本脚本也无能为力。
